"""v07_meeting_proposals

Revision ID: 0840fe70d5ce
Revises: 33074ebc50b0
Create Date: 2026-06-27 13:12:13.563439

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0840fe70d5ce'
down_revision: Union[str, None] = '33074ebc50b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
