"""add_agent_fields_and_execution_table

Revision ID: 24b8353ad754
Revises: 4ab2071f433f
Create Date: 2026-06-27 01:37:55.077427

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '24b8353ad754'
down_revision: Union[str, None] = '4ab2071f433f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agents', sa.Column('allowed_tools', sa.Text(), nullable=True))
    op.add_column('agents', sa.Column('max_execution_time', sa.Integer(), nullable=True))
    op.add_column('agents', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agents', 'updated_at')
    op.drop_column('agents', 'max_execution_time')
    op.drop_column('agents', 'allowed_tools')
    # ### end Alembic commands ###
