"""v07_add_google_event_id_to_calendar_events

Revision ID: 33074ebc50b0
Revises: f94e0572d70d
Create Date: 2026-06-27 12:25:25.048481

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '33074ebc50b0'
down_revision: Union[str, None] = 'f94e0572d70d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('calendar_events', sa.Column('google_event_id', sa.String(length=200), nullable=True))
    op.add_column('calendar_events', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('calendar_events', 'updated_at')
    op.drop_column('calendar_events', 'google_event_id')
    # ### end Alembic commands ###
