"""v07_extra_redesign_auto_reply_rules

Revision ID: 48b15869c4e3
Revises: 0840fe70d5ce
Create Date: 2026-06-27 18:22:32.744602

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '48b15869c4e3'
down_revision: Union[str, None] = '0840fe70d5ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('email_auto_reply_rules', sa.Column('sender_emails', sa.Text(), nullable=True))
    op.add_column('email_auto_reply_rules', sa.Column('sender_domains', sa.Text(), nullable=True))
    op.add_column('email_auto_reply_rules', sa.Column('action', sa.String(length=20), nullable=True))
    op.add_column('email_auto_reply_rules', sa.Column('detect_meeting_with_ia', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('email_auto_reply_rules', 'detect_meeting_with_ia')
    op.drop_column('email_auto_reply_rules', 'action')
    op.drop_column('email_auto_reply_rules', 'sender_domains')
    op.drop_column('email_auto_reply_rules', 'sender_emails')
    # ### end Alembic commands ###
