"""v07_extra_email_activity_log_and_optional_template

Revision ID: bff7a3fd8d7d
Revises: 48b15869c4e3
Create Date: 2026-06-27 19:15:03.489989

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bff7a3fd8d7d'
down_revision: Union[str, None] = '48b15869c4e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
