"""v07_email_calendar_auto_reply_and_availability

Revision ID: f94e0572d70d
Revises: 25c926be5811
Create Date: 2026-06-27 12:18:56.516330

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f94e0572d70d'
down_revision: Union[str, None] = '25c926be5811'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
